replicaCount: 1
namespace: ci-cd
name: jenkins
image:
  repository: jfrog.it-academy.by/public/jenkins-ci
  pullPolicy: IfNotPresent
  tag: "I_Sorokatyi"

service:
  htport: 8080
  jnlport: 50000


JenkinsAuthConfig: /var/jenkins_home/init.groovy.d/basic-security.groovy
JACsubPath: basic-security.groovy
JenkinsConfigYaml: /var/jenkins_home/casc_configs/jenkins.yaml
JCYsubPath: jenkins.yaml
JenkinsConfig: /var/jenkins_home
configMap:
   basic_name: basic-security
   jenkins_name: jenkins-config
nfs:
   server: 192.168.37.105
   path: /mnt/IT-Academy/nfs-data/sa2-23-23/IvanSorokatyi/jenkins-helm-package

ingress:
  name: ingress-jenkins
  enabled: true
  className: ""
  hosts:
    host: jenkins.k8s-19.sa

resources: 
   limits:
     cpu: 2000m
     memory: 2000Mi
   requests:
     cpu: 2000m
     memory: 2000Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}